version: '3.8'

services:
  web:
    build: .
    container_name: scrapeview-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./downloads:/app/downloads
      - ./sqlite.db:/app/sqlite.db
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

volumes:
  downloads:
  sqlite_data: 